### ISSUE TITLE
Dropdown menu animation lag

### ISSUE THREAD

**Issue by r3fl3x** [craftwerkberlin/bootscore#1]
The Dropdown menu square is freezing in one moment when expanding and collapsing, can`t find is it css or js bug.

**Comment by crftwrk** [comment]
Hi,

which header.php do you use? 

The only thing i did is adding a slide animation to the navbar dropdown menu in /js/theme.js line 114 to 126. Everything other is straight Bootstrap. So, can you please provide a link or a screenshot to see that freezing?

Best regards

Basti

**Comment by crftwrk** [comment]
Fixed in version 3.3.0

This will close open offcanvas, cart, collapsed menu, dropdown menu and opac on window resize:

`jQuery(document).ready(function ($) {
    window.onresize = function () {
        $('.opac').removeClass('visible');
        $('.offcanvas-collapse-left, .cart-right, .offcanvas-collapse, .toggler-icon-animated').removeClass('open');
        $('.navbar-nav .dropdown-menu, .navbar-collapse').removeClass('show');
        $(".navbar-nav .dropdown-menu").removeAttr("style");
    }
});
`
