### ISSUE TITLE
Blog posts view - missing linebreak (html tags) in excerpt.

### ISSUE THREAD

**Issue by r3fl3x** [craftwerkberlin/bootscore#2]
I solve it by adding an extra function in my child theme functions file.

**Comment by crftwrk** [comment]
Hi,

do you mean the "Read more" link in the excerpt displayed inline? Its a function in function.php in line 370 which removes the paragraph tag around it. I will make this function pluggable in next update.

Best regards

Basti

**Comment by crftwrk** [comment]
This function is now pluggable in version 3.3.0. Please update the theme.

You can add this into the child theme functions.php:

    function bs_read_more( $more ) { 
    }
    add_filter('the_excerpt', 'wpautop');
