### ISSUE TITLE
Page speed 

### ISSUE THREAD

**Issue by alanvidoc** [craftwerkberlin/bootscore#4]
Hi, this project looks interesting, but please don't forget about optimization and speed.

[pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbootscore.me%2F)

Thank you for your work!

**Comment by crftwrk** [comment]
Hi,

use plugin like https://de.wordpress.org/plugins/jch-optimize/ or https://de.wordpress.org/plugins/autoptimize/ for page speed. This is plain Bootstrap and WordPress.
